
#########################################################################################
########################    Bioinformatics Stronghold    ################################
#########################################################################################

### problem

s = 'AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC'

print (s)

len(s)

count_A = s.count('A')
count_T = s.count('T')
count_G = s.count('G')
count_C = s.count('C')

print (count_A, count_C, count_G, count_T)


## dataset

dataset = 'CGCTATAGAACGAGTAGTAATGGGTGTATAGCATATTAACTATGCTGGGTATTCGATTCTCTCCTAGCCATTATAAGTGTCTTTCGATTCAGGCGTGCGCCCGTAGCGAGTCCGACGAATAAGGAGTAGCGACTGAGTTCAACTGCCCGAGGCCGCAATCTGCAGCCTCACCCTTAAGTGCTGCTGTACCGCACAGAACGCAGGTGTTCTCCAGGCTCGAATACAGTTCCGGGTGATCTCGGACTTCTGCCACAACGTGAGCTGTTCATTTTTGCGCAACCTACTGAGAGCTGAGAGGCCCACCTTTATAACTGGGGCCTTCGTCCAAAGGCCTTAACGGAGCAGCACTAAACAGTTTAAAAACCCTGTGTCCCGTCTCCATAGATTAAACTTGGATGTCATAAGCACTTGTTTTTTGGGACTATGGGTTGAATTCACCCGGGTTCAGAAGAATCGCGTACTAAGCATCCTAAGAGGACATTGTAGCCGATATCACTGAGGCTGAGACCGATCTTGCTTTGAGCACGTCAAAAAAGGAAAAGAGGGGGATGGCCATTGGGGAGACAGGTCATAGGTGAAACTAGACATCATCTATTATTCATAAAAACCTTTTGGCTGTAACGCATGGGTCCAATTTCGGAGCGCACAAATCCGTGGGTTTTTCTGCTCTTCCCGTTTGGAGAAGAGGAGGCTCCAACCTCCAGTGCCACTGCCACACGTAATTACAATTCTGTCTTAACTACCGTGGAAAGCACCGCGCGCAGACGCGCCGTTCTAATTGCGAATACAGCCAGACACTAAGCAGGGTCAGTATTTTCTAACCGAAAGCTGGCTAGGTTGTAATGTCGCCGGTGATTACCGATTGAGTGGTGTTTGCAATGCCTCCA'

print (dataset)

len(dataset)

count_A = dataset.count('A')
count_T = dataset.count('T')
count_G = dataset.count('G')
count_C = dataset.count('C')

print (count_A, count_C, count_G, count_T)

